exclude_paths:
  - '.bundle/**'
  - 'spec/**/*'
  - 'benchmarks/**/*'
  - '*.min.js'
  - '**/tests/**'
  - '**/functionaltests/**/*'
  - 'wiki/**'
  - '.github/**'
  - 'CODE_OF_CONDUCT.md'
  - 'CONTRIBUTING.md'

coverage:
  exclude_paths:
    - 'src/test/resources/*.json'