#! /bin/bash
success=0
failure=0

command="test"
times=1

if [ "$1" != "" ];
then
  command=$1
fi

if [ "$2" != "" ];
then
  times=$2
fi

command="mvn ""$command"

echo "Command: $command"
echo "Times: $times"

function do_test {
  echo "########################################"
  echo "########### RUNNING TESTS ##############"
  echo "########################################"

  $command > tmp_output

  if [ $? -eq 0 ]; then
    echo OK
    success=$((success + 1))
    rm tmp_output
    #mv tmp_output test_run_"$1"_output_SUCCESS.log
  else
    echo FAIL
    failure=$((failure + 1))
    mv tmp_output test_run_"$1"_output_FAILURE.log
  fi
}

for i in $(seq 1 "$times")
do
  echo "Test number $i"
  do_test "$i"
done

echo "Successfull: $success  ||  Failures: $failure"
