#! /bin/bash
success=0
failure=0

function do_test {
  echo "########################################"
  echo "########### RUNNING TESTS ##############"
  echo "########################################"

  mvn clean -Dsurefire.rerunFailingTestsCount=2 test
  if [ $? -eq 0 ]; then
    echo OK
    success=$((success + 1))
  else
    echo FAIL
    failure=$((failure + 1))
  fi
}

for i in 1 2 3 4 5 6 7 8
do
  echo "Looping ... number $i"
  do_test
done

echo "Successfull: $success  ||  Failures: $failure"
