#! /bin/bash
success=0
failure=0

command="test"
times=1

if [ "$1" != "" ];
then
  command=$1
fi

if [ "$2" != "" ];
then
  times=$2
fi


echo "Command: $command"
echo "Times: $times"

function do_test {
  echo "########################################"
  echo "########### RUNNING TESTS ##############"
  echo "########################################"

  #mvn clean -Dsurefire.rerunFailingTestsCount=2 test
  mvn "$command"
  if [ $? -eq 0 ]; then
    echo OK
    success=$((success + 1))
  else
    echo FAIL
    failure=$((failure + 1))
  fi
}
#times_run=0

for i in $(seq 1 "$times")
do
  echo "Test number $i"
  do_test
done

echo "Successfull: $success  ||  Failures: $failure"
