description: This class handles requests related to authentication.
get:
  description: This method checks if security is enabled.
  responses:
    200:
      body:
        application/string:

/login:
  get:
    description: This method returns a logged in user.
    responses:
      200:
        body:
          application/string:
