description: This class searches for failed notifications in the database.
get:
  description: This method returns failed notification(s) given the subscription name(s).
  queryParameters:
    subscriptionNames:
      displayName: subscriptionNames
      type: string
      description: List of subscription names separated by comma
      example: Subscription_1
      required: true
  responses:
    200:
      body:
        application/json:
