description: This class provides information about Eiffel Intelligence backend.
get:
    description: This method retrieves backend instance information.
    responses:
       200:
         body:
           application/json:
