description: This class retrieves aggregated objects given a free style query. Criteria is
             required to have in the request body, while options and filter are optional.
post:
  description: The REST POST method is used to query aggregated abjects with the
               requested criteria, which are present in the request body.
  body:
    application/json:
      schema: queryBody
  responses:
    200:
      body:
        application/json:
