description: This service for the execute the rules over the Json Content
/rule-check:
  post:
    description: This call for run the jmespath rule object or rule on the JSON object
    displayName: checkRule
    body:
      application/json:
        schema: ruleCheckBody
    responses:
      200:
        body:
          application/string:

  /aggregation:
    post:
      description: This call for run the jmespath rule objects on the Json array of objects, we get aggregation Object as output
      displayName: findAggregation
      body:
        application/json:
          schema: rulesCheckBody
      responses:
        200:
          body:
            application/string:

  /testRulePageEnabled:
    get:
      description: This call for the current status of test rule entry point, we get status as output
      displayName: findTestRuleServiceStatus
      responses:
        200:
          body:
            application/string:
               example: "status: false"
