description: Using the root endpoint one can check if rule tests are enabled in the EI instance.
get:
  description: This method checks if the possibility to test rules has been enabled in Eiffel Intelligence.
  responses:
    200:
      body:
        application/string:
          example: "status: false"

/run-single-rule:
  post:
    description: This method extracts data from a single Eiffel event based on the given JMESPath expression.
    body:
      application/json:
        schema: ruleCheckBody
    responses:
      200:
        body:
          application/string:

/run-full-aggregation:
  post:
    description: This method extracts data from the given list of Eiffel events, based on a set of rules and returns an aggregated object.
    body:
      application/json:
        schema: rulesCheckBody
    responses:
      200:
        body:
          application/string:
