description: This class returns status information about Eiffel Intelligence and it's dependencies.
get:
  description: returns status information about Eiffel Intelligence and services Eiffel Intelligence is dependent on.
  responses:
    200:
      body:
        application/json:
        