description: Provides REST API for handling subscriptions.
get:
  description: This method retrieves all subscriptions from the database. Specific subscriptions can be retrieved by using the 'subscriptionName' parameter.
  queryParameters:
    subscriptionName:
      description: List of subscription names separated by comma
      type: string
      required: false
  responses:
    200:
      body:
        application/json:

post:
  description: This method creates new subscription(s) and saves in the database. The name of a subscription must be unique.
  body:
    application/json:
      schema: subscriptionList
  responses:
    200:
      body:
        application/json:

put:
  description: This method modifies existing subscriptions.
  body:
    application/json:
      schema: subscriptionList
  responses:
    200:
      body:
        application/json:

delete:
  description: This method removes subscriptions from the database. It requires a list of names by using the 'subscriptionName' parameter
  queryParameters:
    subscriptionName:
      description: List of subscription names separated by comma.
      type: string
      required: true

/{subscriptionName}:
  uriParameters:
    subscriptionName:
      displayName: subscriptionName
      description: The name of the subscription.
      required: true
      type: string

  get:
    description: This method returns the subscription for the given subscription name.
    responses:
      200:
        body:
          application/json:

  delete:
    description: This method removes the subscription from the database for the given subscription name.
    responses:
      200:
        body:
          application/json:
