description: Provides REST API for handling subscriptions.
get:
  description: This method retrieves all subscriptions from the database.
  responses:
    200:
      body:
        application/json:

post:
  description: This method creates new subscription(s) and saves in the database. The name of a subscription must be unique.
  body:
    application/json:
      schema: subscriptionList
  responses:
    200:
      body:
        application/json:

put:
  description: This method modifies existing subscriptions.
  body:
    application/json:
      schema: subscriptionList
  responses:
    200:
      body:
        application/json:

/{subscriptionNames}:
  uriParameters:
    subscriptionNames:
      displayName: SubscriptionNames
      description: The names of the subscriptions separated by comma.
      required: true
      type: string

  get:
    description: This method returns the subscriptions for the given subscription names.
    responses:
      200:
        body:
          application/json:

  delete:
    description: This method removes the subscriptions from the database for the given subscription names.
    responses:
      200:
        body:
          application/json:
