description: This class is responsible for providing templates of rules, Eiffel events and subscriptions.
get:
  description: This method returns a list of endpoints for downloading templates.
  responses:
    200:
      body:
        application/string:

/subscriptions:
  get:
    description: This method returns subscription templates.
    responses:
      200:
        body:
          application/string:

/rules:
  get:
    description: This method returns a template for rules.
    responses:
      200:
        body:
          application/string:

/events:
  get:
    description: This method returns a template for Eiffel events.
    responses:
      200:
        body:
          application/string:
