  get:
    description: This call for checking if security is enabled
    displayName: check security
    responses:
      200:
        body:
          application/string:

  /login:
    get:
      description: This call for getting logged in user
      displayName: login
      responses:
        200:
          body:
            application/string:

  /checkStatus:
    get:
      description: This call for checking backend status
      displayName: check status
      responses:
        200:
          body:
            application/string:
