subscription: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.Subscription",
       "definitions":{
       },
       "properties":{
          "aggregationtype":{
             "type":"string"
          },
          "created":{
             "type":"long"
          },
          "notificationMeta":{
             "type":"string"
          },
          "notificationType":{
             "type":"string"
          },
          "restPostBodyMediaType":{
                       "type":"string"
                    },
          "notificationMessageKeyValues":{
                       "items":{
                              "properties":{
                                 "formkey":{
                                    "type":"string"
                                 },
                                 "formvalue":{
                                     "type":"string"
                                            }
                              },
                              "type":"object"
                           },
                           "type":"array"
          },
          "repeat":{
             "type":"boolean"
          },
          "requirements":{
             "items":{
                "properties":{
                   "conditions":{
                      "items":{
                         "properties":{
                            "jmespath":{
                               "type":"string"
                            }
                         },
                         "type":"object"
                      },
                      "type":"array"
                   }
                },
                "type":"object"
             },
             "type":"array"
          },
          "subscriptionName":{
             "type":"string"
          },
          "userName":{
             "type":"string"
          }
       },
       "type":"object"
    }
subscriptionList: |
    {
       "type": "array",
       "items": {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.Subscription",
       "definitions":{
       },
       "properties":{
          "aggregationtype":{
             "type":"string"
          },
          "created":{
             "type":"long"
          },
          "notificationMeta":{
             "type":"string"
          },
          "notificationType":{
             "type":"string"
          },
          "restPostBodyMediaType":{
                       "type":"string"
                    },
          "notificationMessageKeyValues":{
                       "items":{
                              "properties":{
                                 "formkey":{
                                    "type":"string"
                                 },
                                 "formvalue":{
                                     "type":"string"
                                            }
                              },
                              "type":"object"
                           },
                           "type":"array"
                    },
          "repeat":{
             "type":"boolean"
          },
          "requirements":{
             "items":{
                "properties":{
                   "conditions":{
                      "items":{
                         "properties":{
                            "jmespath":{
                               "type":"string"
                            }
                         },
                         "type":"object"
                      },
                      "type":"array"
                   }
                },
                "type":"object"
             },
             "type":"array"
          },
          "subscriptionName":{
             "type":"string"
          },
          "userName":{
             "type":"string"
          }
       },
       "type":"object"
    }
    }
subscriptionResponse: |
    {
       "type": "array",
       "items": {
          "$schema":"http://json-schema.org/draft-04/schema#",
          "javaType":"com.ericsson.ei.controller.model.SubscriptionResponse",
          "definitions":{
          },
          "properties":{
             "subscription":{
                "type":"string"
             },
             "reason":{
                "type":"string"
             }
          },
          "type":"object"
       }
    }
getSubscriptionResponse: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.GetSubscriptionResponse",
          "properties":{
             "foundSubscriptions":{
                "type":"array",
                "items":{
                   "javaType":"com.ericsson.ei.controller.model.Subscription"
                }
             },
             "notFoundSubscriptions":{
                "type":"array",
                "items":{
                   "type":"string"
                }
             }
          },
       "type":"object"
    }
stringServiceResponse: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.QueryResponse",
       "properties":{
          "responseEntity":{
             "type":"string"
          }
       },
       "type":"object"
    }
rulesCheckBody: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.RulesCheckBody",
          "properties":{
             "listRulesJson":{
                "type":"array"
             },
             "listEventsJson":{
                "type":"array"
             }
          },
       "type":"object"
    }
ruleCheckBody: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.RuleCheckBody",
          "properties":{
             "rule":{
                "type":"object"
             },
             "event":{
                "type":"object"
             }
          },
       "type":"object"
    }
queryBody: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.QueryBody",
       "properties":{
             "criteria":{
                "type":"object"
             },
             "options":{
                "type":"object",
                "required":"false"
             }
          },
       "type":"object"
    }
