subscription: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.Subscription",
       "definitions":{
       },
       "properties":{
          "aggregationtype":{
             "type":"string"
          },
          "created":{
             "type":"string"
          },
          "notificationMessage":{
             "type":"string"
          },
          "notificationMeta":{
             "type":"string"
          },
          "notificationType":{
             "type":"string"
          },
          "repeat":{
             "type":"boolean"
          },
          "requirements":{
             "items":{
                "properties":{
                   "conditions":{
                      "items":{
                         "properties":{
                            "jmespath":{
                               "type":"string"
                            }
                         },
                         "type":"object"
                      },
                      "type":"array"
                   }
                },
                "type":"object"
             },
             "type":"array"
          },
          "subscriptionName":{
             "type":"string"
          }
       },
       "type":"object"
    }
subscriptionList: |
    {
       "type": "array",
       "items": {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.Subscription",
       "definitions":{
       },
       "properties":{
          "aggregationtype":{
             "type":"string"
          },
          "created":{
             "type":"string"
          },
          "notificationMessage":{
             "type":"string"
          },
          "notificationMeta":{
             "type":"string"
          },
          "notificationType":{
             "type":"string"
          },
          "repeat":{
             "type":"boolean"
          },
          "requirements":{
             "items":{
                "properties":{
                   "conditions":{
                      "items":{
                         "properties":{
                            "jmespath":{
                               "type":"string"
                            }
                         },
                         "type":"object"
                      },
                      "type":"array"
                   }
                },
                "type":"object"
             },
             "type":"array"
          },
          "subscriptionName":{
             "type":"string"
          }
       },
       "type":"object"
    }
    }
subscriptionResponse: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.SubscriptionResponse",
       "definitions":{
       },
       "properties":{
          "msg":{
             "type":"string"
          },
          "statusCode":{
             "type":"integer"
          },
          "responseEntity":{
             "type":"string"
          }
       },
       "type":"object"
    }
stringServiceResponse: |
    {
       "$schema":"http://json-schema.org/draft-04/schema#",
       "javaType":"com.ericsson.ei.controller.model.QueryResponse",
       "properties":{
          "responseEntity":{
             "type":"string"
          }
       },
       "type":"object"
    }