#%RAML 0.8
  schemas:
    - !include common-schema.raml
  resourceTypes:
  - standard:
      get?:
        responses:          
          400:
            description: |
              The request sent to the server contains data which is not as expected e.g. incorrect Subscription Name
          404:
            description: |
              The requested resource was not found                     
      put?:
        responses:          
          404:
            description: |
              The requested resource on which the modification is being attempted was not found              
      delete?:
        responses:          
          404:
            description: | 
              The requested resource to delete was not found 
 
  title: Subscriptions Services and EI Query Services
  version: ${project.version}
  mediaType: application/json
  baseUri: /
  /subscriptions: !include subscription.raml
  /query: !include query.raml
  /queryAggregatedObject: !include query-aggregated_object.raml
  /queryMissedNotifications: !include query-missed_notifications.raml
  /jmespathrule: !include jmespath.raml
  /download: !include template.raml
  /rules: !include rules.raml