#%RAML 1.0
schemas:
  subscription: !include schemas/sub.schema
  subscriptionList: !include schemas/sub_list.schema
  subscriptionResponse: !include schemas/sub_response.schema
  getSubscriptionResponse: !include schemas/get_sub_response.schema
  queryBody: !include schemas/query_body.schema
  stringServiceResponse: !include schemas/string_service_response.schema
  ruleCheckBody: !include schemas/rule_check_body.schema
  rulesCheckBody: !include schemas/rules_check_body.schema

resourceTypes:
  standard:
    get?:
      responses:
        400:
          description: |
            The request sent to the server contains data which is not as expected e.g. incorrect Subscription Name
        404:
          description: |
            The requested resource was not found
    put?:
      responses:
        404:
          description: |
            The requested resource on which the modification is being attempted was not found
    delete?:
      responses:
        404:
          description: |
            The requested resource to delete was not found

title: Eiffel Intelligence
version: 2
mediaType: application/json
baseUri: /
/subscriptions: !include resourceTypes/subscription.raml
/aggregated-objects: !include resourceTypes/aggregated_object.raml
/templates: !include resourceTypes/templates.raml
/failed-notifications: !include resourceTypes/failed-notifications.raml
/authentication: !include resourceTypes/authentication.raml
/rule-test: !include resourceTypes/rule-test.raml
/rules: !include resourceTypes/rules.raml
/status: !include resourceTypes/status.raml
/information: !include resourceTypes/instance_info.raml
