 /freestylequery:
      post:
        body:
         application/json:
        responses:
          200:
            body:
              application/json:
                schema: freestylequery
      get:
        body:
          application/json:
        responses:
           200:
             body:
               application/json:
                 schema: freestylequery
