    description: |
      Provides interaction with InstanceInfo resource
    get:
        description: |
          List of all instance information
        responses:
           200:
             body:
               application/json: