
 /runRule:
      post:
        body:
         multipart/form-data:
            formParameters: 
              farg:
                displayName: formArg
                type: string
                description: form parameter
                required: true            
                         
        queryParameters:
          arg1: 
            displayName: arg1
            type: string
            description: expression
            example: a.b
            required: true
        
   
        responses:
          200:        
            body:
              application/string:
                  