get:
  queryParameters:
    id:
      displayName: id
      type: string
      description: Id of the aggregatedObject
      example: 6acc3c87-75e0-4b6d-88f5-b1a5d4e62b44
      required: true
  responses:
    200:
      body:
        application/json:
          schema: stringServiceResponse