post:
  description: The REST POST method is used to query Aggregated Objects with the
               criterias requested, which are present in the request body of the
               request URL.
  body:
    application/json:
      schema: queryBody
  responses:
    200:
      body:
        application/json:
