get:
  description: List the missed notification based on the subscriptionName in the query parameter.
  queryParameters:
    subscriptionName:
      displayName: subscriptionName
      type: string
      description: SubscriptionName of the Missed Notification
      example: Subscription_1
      required: true
  responses:
    200:
      body:
        application/json:
          schema: stringServiceResponse