

    description: This service for the execute the rules over the Json Content
    /rule-check:
      post:
        description: This call for run the jmespath rule object or rule on the JSON object
        displayName: checkRule
        body:
          multipart/form-data:
            formParameters: 
              jsonContent:
                displayName: jsonContent
                type: string
                description: json content as form parameter
                required: true
        queryParameters:
          rule: 
            displayName: rule
            type: string
            description: jmespath rule expression
            example: a.b
            required: true      
        responses:
          200:
            body:
              application/string:
        
      /aggregation:
        post:
          description: This call for run the jmespath rule objects on the Json array of objects, we get aggregation Object as output
          displayName: findAggregation
          body:
            multipart/form-data:
              formParameters: 
                listRulesJson:
                  description: This variable for the list of rules in json format, for find the aggregation object
                  displayName: listRulesJson
                  type: string
                  required: true 
                listEventsJson:
                 description: This variable for the list of Events in json format
                 displayName: listEventsJson
                 type: string
                 required: true
          responses:
            200:
              body:
                application/string: