

    description: Provides interaction with Subscription resource
    get:
      description: Fetches all subscriptions as list.
      responses:
        200:        
          body:
            application/json:
              
    post:
      description: Takes the subscription rules, the name for subscription and the user name of the person registering this subscription and saves the subscription in subscription database. The name needs to be unique. 
      body:
        application/json:
          schema: subscriptionList
      responses:
        200:
          body:
            application/json:
              schema: subscriptionResponse

    put:      
      description: Modify existing Subscriptions.
      body:
        application/json:
          schema: subscriptionList
      responses:
        200:        
          body:
            application/json:
              schema: subscriptionResponse
                
    /{subscriptionNames}:
      uriParameters:
        subscriptionNames:
          displayName: SubscriptionNames
          description: The names of the Subscriptions separated by comma.
          required: true
          type: string
      
      get:
        description: Returns the subscriptions for the given subscription names.
        responses:
          200:        
            body:
              application/json:
                schema: getSubscriptionResponse



      delete:
        description: Removes the subscriptions from the database for the given subscription names.
        responses:
          200:        
            body:
              application/json:
                schema: subscriptionResponse