

    description: Provides interaction with Subscription resource
    get:
      description: List the names of all subscriptions      
      responses:
        200:        
          body:
            application/json:
              schema: subscriptionList
              
    post:
      description: Takes the subscription rules, the name for subscription and the user name of the person registering this subscription and saves the subscription in subscription database. The name needs to be unique. 
      body:
        application/json:
          schema: subscription  

    put:      
      description: Modify an existing Subscription. 
      body:
        application/json:
          schema: subscription
      responses:
        200:        
          body:
            application/json:
              schema: subscriptionResponse            
                
    /{subscriptionName}:    
      uriParameters:
        subscriptionName:
          displayName: SubscriptionName
          description: |
            The name of the Subscription for info
            required: true
            type: string
      
      get:
        description: Returns the subscription rules for given subscription name. 
        responses:
          200:        
            body:
              application/json:
                schema: subscriptionList
              
        
              
      delete:
        description: Removes the subscription from the database.
        responses:
          200:        
            body:
              application/json:
                schema: subscriptionResponse