
package com.ericsson.ei.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


/**
 * No description
 * (Generated with springmvc-raml-parser v.2.0.4)
 * 
 */
@RestController
@RequestMapping(value = "/query", produces = "application/json")
@Validated
public class QueryController {


    /**
     * The REST POST method is used to query Aggregated Objects with the criterias requested, which are present in the request body of the request URL.
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity<?> createQuery() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
