
package com.ericsson.ei.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


/**
 * No description
 * (Generated with springmvc-raml-parser v.2.0.4)
 * 
 */
@RestController
@RequestMapping(value = "/rules/rule-check", produces = "application/json")
@Validated
public class RuleCheckController {


    /**
     * This call for run the jmespath rule object or rule on the JSON object
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity<?> createRuleCheck() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * This call for run the jmespath rule objects on the Json array of objects, we get aggregation Object as output
     * 
     */
    @RequestMapping(value = "/aggregation", method = RequestMethod.POST)
    public ResponseEntity<?> createRuleCheck() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * This call for the current status of test rule entry point, we get status as output
     * 
     */
    @RequestMapping(value = "/testRulePageEnabled", method = RequestMethod.GET)
    public ResponseEntity<?> getObject() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
