
package com.ericsson.ei.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


/**
 * Provides interaction with Subscription resource
 * (Generated with springmvc-raml-parser v.2.0.4)
 * 
 */
@RestController
@RequestMapping(value = "/subscriptions", produces = "application/json")
@Validated
public class SubscriptionController {


    /**
     * Fetches all subscriptions as list.
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public ResponseEntity<?> getObject() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Takes the subscription rules, the name for subscription and the user name of the person registering this subscription and saves the subscription in subscription database. The name needs to be unique.
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity<?> createSubscriptions() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Modify existing Subscriptions.
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.PUT)
    public ResponseEntity<?> updateSubscriptions() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Returns the subscriptions for the given subscription names.
     * 
     */
    @RequestMapping(value = "/{subscriptionNames}", method = RequestMethod.GET)
    public ResponseEntity<?> getObjectBySubscriptionNames(
        @PathVariable
        String subscriptionNames) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Removes the subscriptions from the database for the given subscription names.
     * 
     */
    @RequestMapping(value = "/{subscriptionNames}", method = RequestMethod.DELETE)
    public ResponseEntity<?> deleteSubscriptionBySubscriptionNames(
        @PathVariable
        String subscriptionNames) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
